nome = str(input('Digite seu nome: ')).strip()
print('Analisando seu nome...')
print('Seu nome em maiúsculo é: {}'.format(nome.upper()))
print('Seu nome em minúsclo é: {}'.format(nome.lower()))
separa = nome.split()
print('Seu primeiro nome é {} e tem {} caracteres'.format(separa[0], len(separa[0])))